services:
  api:
    build: .
    container_name: agent-io
    restart: always
    environment:
      # Variables de entorno para tu API
      NODE_ENV: production
      DB_HOST: postgres_db  # Nombre del contenedor de PostgreSQL
      DB_PORT: 5432
      DB_USER: nala
      DB_PASSWORD: nala
      DB_NAME: nala_db
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    external: true